spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell
#    url: jdbc:mysql://192.168.43.82:3306/sell
    username: root
    password: 123456
  jpa:
    show-sql: true
server:
  context-path: /sell